// ---------------- IMPORTS ----------------

// 'generateText' is a function provided by the AI library
// It is the main tool we use to ask the AI to produce text, like a magic pen
// We can give it instructions, and it will return a story, poem, or any text we want
import { generateText } from "ai";

// 'google' is a function from the Google AI SDK
// It allows us to connect to Google’s generative AI models, like Gemini 2.0 Flash
// Without this, we cannot send requests to Google’s AI service
import { google } from "@ai-sdk/google";

// ---------------- POST HANDLER ----------------

// The POST function runs whenever the frontend sends a request to "/api/chat"
// POST is a method used to send information (like characters and genre) to the server
// Think of it as the user clicking "Generate Story" and sending instructions to the backend
export async function POST(req) {
  try {
    // Read the body of the request from the frontend
    // This contains the characters and genre the user typed
    // req.json() parses the incoming JSON so we can use it as JavaScript objects
    const body = await req.json();

    // ---------------- HANDLE DEFAULTS ----------------

    // Extract the list of characters from the request
    // If the user did not provide any, use a default list ["Alice", "Bob"]
    const characters = body.characters || ["Alice", "Bob"];

    // Extract the genre of the story
    // If nothing is provided, default to "Adventure"
    const genre = body.genre || "Physics";

    // ---------------- CREATE PROMPT ----------------

    // Construct the prompt for the AI
    // The prompt is like a detailed instruction to a human writer:
    // "Write a short story (about 120 words) in this genre, with these characters"
    const prompt = `Create a short (about 240 words) assignment in the ${genre} subject using these characters: ${characters.join(", ")}. Include instructions and expected outcomes.`;

    // ---------------- SETUP AI MODEL ----------------

    // Initialize the AI model using the Google AI SDK
    // 'gemini-2.0-flash' is the model name — think of it as choosing which AI brain will write the story
    // The API key proves that we are allowed to use Google’s AI service
    // Storing the key in process.env keeps it secret and safe
    const model = google("gemini-2.0-flash", {
      apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY,
    });

    // ---------------- GENERATE STORY ----------------

    // Call generateText to produce the story
    // We provide:
    // 1. model: the AI brain we set up
    // 2. prompt: the instructions we wrote
    // 3. maxOutputTokens: limits the story length
    //    - Tokens are small chunks of words; 180 tokens ≈ 120 words
    //    - This ensures the AI generates a concise story instead of a long essay
    const result = await generateText({
      model,             // The AI model that will generate the text
      prompt,            // The instructions for the AI
      maxOutputTokens: 360, // Limits the story length to roughly 120 words
    });

    // ---------------- SEND RESPONSE TO FRONTEND ----------------

    // result.text contains the story generated by AI
    // We send it back as JSON so the frontend can display it
    return new Response(JSON.stringify({ story: result.text }), { status: 200 });

  } catch (err) {
    // ---------------- ERROR HANDLING ----------------

    // If something goes wrong, log the full error for debugging
    console.error("Full API Error:", err);

    // Send an error message back to the frontend so the user knows something failed
    // We try to use err.message first, or convert the error object to string, or fallback to a generic message
    return new Response(JSON.stringify({
      error: err.message || JSON.stringify(err) || "Unknown error from API"
    }), { status: 500 }); // HTTP 500 = server-side error
  }
}
